name: docker-embedded-software-ci

on:
  push:
    branches: master

jobs:
  build:
    runs-on: debian-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3.2.0
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: docker buildx build --tag hamburml/docker-embedded-software-ci:latest --platform linux/amd64,linux/arm/v7,linux/arm64 .
